export const ADD_LATEST_TOTALS = 'ADD_LATEST_TOTALS';
export const LATEST_TOTALS_FAILED = 'LATEST_TOTALS_FAILED';
export const LATEST_TOTALS_LOADING = 'LATEST_TOTALS_LOADING';
export const ADD_ALL_COUNTRIES = 'ADD_ALL_COUNTRIES';
export const ALL_COUNTRIES_FAILED = 'ALL_COUNTRIES_FAILED';
export const ALL_COUNTRIES_LOADING = 'ALL_COUNTRIES_LOADING';
